openapi: 3.0.0
info:
  title: Edifice - Explorer - API 🚧🚧
  description: This part represant the documentation of the Edifice api use in explorer module
  version: 4.10.0
servers:
  - url: /

tags:
  - name: explorer
    description: 🚧 //TODO
  - name: folders
    description: 🚧 //TODO
  - name: job
    description: 🚧 //TODO

paths:
  /explorer/context:
    get:
      tags:
        - explorer
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /explorer/resources:
    get:
      tags:
        - explorer
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /explorer/folders:
    get:
      tags:
        - folders
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

    post:
      tags:
        - folders
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /explorer/folders/{id}:
    parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
    get:
      tags:
        - folders
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

    put:
      tags:
        - folders
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /explorer/folders/{id}/move:
    parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string

    post:
      tags:
        - folders
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /explorer/trash:
    put:
      tags:
        - explorer
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /explorer/restore:
    put:
      tags:
        - explorer
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /explorer:
    delete:
      tags:
        - explorer
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /explorer/share/{application}/{type}/{resourceId}:
    parameters:
      - name: application
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: type
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: resourceId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string

    put:
      tags:
        - explorer
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /explorer/metrics:
    get:
      tags:
        - explorer
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /explorer/simulate/resource:
    get:
      tags:
        - explorer
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /explorer/simulate/folders/{id}:
    parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
    get:
      tags:
        - folders
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /explorer/job/trigger:
    get:
      tags:
        - job
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /explorer/job/status/{method}:
    parameters:
      - name: method
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
    get:
      tags:
        - job
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /explorer/reindex/{application}/{type}:
    parameters:
      - name: application
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: type
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
    get:
      tags:
        - explorer
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /explorer/mute:
    get:
      tags:
        - explorer
      summary: 🚧 //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

components:
  schemas:
    Error:
      required:
        - message
      type: object
      properties:
        message:
          type: string
          description: A human-readable error message
  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: "For more information, see https://opendigitaleducation.atlassian.net/wiki/spaces/PUBLIC/pages/1184891013/Connecteur+-+SSO+oAuth2"
      flows:
        authorizationCode:
          authorizationUrl: /auth/oauth2/auth
          tokenUrl: /auth/oauth2/token
          scopes:
            userinfo: Get user's identification information
            conversation: Access to conversation API
